# NLP Exercises

We have five exercises in this section. The exercises are:
1. Build your own tokenizer, where you need to implement two functions to implement a tokenizer based on regular expression.
2. Get tags from Trump speech.
3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.
4. Build your own Bag Of Words implementation using tokenizer created before.
5. Build a 5-gram model and clean up the results.

## Exercise 1. Build your own tokenizer

Build two different tokenizers:
- ``tokenize_sentence``: function tokenizing text into sentences,
- ``tokenize_word``: function tokenizing text into words.

In [10]:
from typing import List
import re

def tokenize_words(text: str) -> list:
    """Tokenize text into words using regex.

    Parameters
    ----------
    text: str
            Text to be tokenized

    Returns
    -------
    List[str]
            List containing words tokenized from text

    """
    text = re.sub(r'([.!?])([A-Z])', r'\1 \2', text)
    text = re.sub(r'(:\w)([A-Z])', r'\1 \2', text)
    time_pattern = r'\d+\.\w+\.\w+\.?'
    times = re.findall(time_pattern, text)
    for i, time in enumerate(times):
        placeholder = f"TIMEPLACEHOLDER{i}"
        text = text.replace(time, placeholder)
    pattern = r'\b[A-Za-z0-9]+(?:[-\'][A-Za-z0-9]+)*\b|(?<!\.)(?:\d+\.\d+)(?!\.)'
    tokens = re.findall(pattern, text)
    
    result = []
    for token in tokens:
        if token.startswith("TIMEPLACEHOLDER"):
            index = int(token[15:])
            result.append(times[index])
        else:
            result.append(token)
            
    return result

def tokenize_sentence(text: str) -> list:
    """Tokenize text into words using regex.

    Parameters
    ----------
    text: str
            Text to be tokenized

    Returns
    -------
    List[str]
            List containing words tokenized from text

    """
    time_pattern = r'\d+\.\w+\.\w+\.?'
    times = re.findall(time_pattern, text)
    
    for i, time in enumerate(times):
        placeholder = f"TIMEPLACEHOLDER{i}"
        text = text.replace(time, placeholder)
    text = text.replace('\\\n', ' ').replace('\\', ' ')
    sentences = []
    pattern = r'[^.!?]+[.!?](?=\s+|[A-Z]|\Z)'
    
    current_position = 0
    for match in re.finditer(pattern, text):
        sentence = match.group().strip()
        sentences.append(sentence)
        current_position = match.end()
    if current_position < len(text):
        remaining = text[current_position:].strip()
        if remaining:
            sentences.append(remaining)

    for i, time in enumerate(times):
        placeholder = f"TIMEPLACEHOLDER{i}"
        sentences = [s.replace(placeholder, time) for s in sentences]
    
    return sentences


text = "Here we go again. I was supposed to add this text later.\
Well, it's 10.p.m. here, and I'm actually having fun making this course. :o\
I hope you are getting along fine with this presentation, I really did try.\
And one last sentence, just so you can test you tokenizers better."

print("Tokenized sentences:")
print(tokenize_sentence(text))

print("Tokenized words:")
print(tokenize_words(text))

Tokenized sentences:
['Here we go again.', 'I was supposed to add this text later.', "Well, it's 10.p.m. here, and I'm actually having fun making this course.", ':oI hope you are getting along fine with this presentation, I really did try.', 'And one last sentence, just so you can test you tokenizers better.']
Tokenized words:
['Here', 'we', 'go', 'again', 'I', 'was', 'supposed', 'to', 'add', 'this', 'text', 'later', 'Well', "it's", '10.p.m.', 'here', 'and', "I'm", 'actually', 'having', 'fun', 'making', 'this', 'course', 'o', 'I', 'hope', 'you', 'are', 'getting', 'along', 'fine', 'with', 'this', 'presentation', 'I', 'really', 'did', 'try', 'And', 'one', 'last', 'sentence', 'just', 'so', 'you', 'can', 'test', 'you', 'tokenizers', 'better']


## Exercise 2. Get tags from Trump speech using NLTK

You should use the ``trump.txt`` file, read it and find the tags for each word. Use NLTK for it.

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk import pos_tag

# Download required NLTK data (only needed first time)
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

file = open("../datasets/trump.txt", "r", encoding="utf-8") 
trump = file.read()
words = word_tokenize(trump)

pos_tags = pos_tag(words)

print("First 20 tagged words:")
for word, tag in pos_tags[:20]:
    print(f"{word}: {tag}")

[nltk_data] Downloading package punkt to /home/uygarpasa/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/uygarpasa/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


First 20 tagged words:
Thank: NNP
you: PRP
very: RB
much: RB
.: .
Mr.: NNP
Speaker: NNP
,: ,
Mr.: NNP
Vice: NNP
President: NNP
,: ,
Members: NNP
of: IN
Congress: NNP
,: ,
the: DT
First: NNP
Lady: NNP
of: IN


## Exercise 3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.

Please use Python list features to get the last 10 sentences and display nouns from it.

In [19]:
import spacy

file = open("../datasets/trump.txt", "r",encoding='utf-8') 
trump = file.read() 

### here comes your code
nlp = spacy.load("en_core_web_sm")
doc = nlp(trump)
sentences = list(doc.sents)[-10:]

for i, sentence in enumerate(sentences, 1):
    nouns = [token.text for token in sentence if token.pos_ == "NOUN"]
    
    print(f"\nSentence {i}:")
    print(f"Text: {sentence.text}")
    print(f"Nouns: {nouns}")



Sentence 1:
Text: When we fulfill this vision, when we celebrate our 250 years of glorious freedom, we will look back on tonight as when this new chapter of American greatness began.
Nouns: ['vision', 'years', 'freedom', 'tonight', 'chapter', 'greatness']

Sentence 2:
Text: The time for small thinking is over.
Nouns: ['time', 'thinking']

Sentence 3:
Text: The time for trivial fights is behind us.
Nouns: ['time', 'fights']

Sentence 4:
Text: We just need the courage to share the dreams that fill our hearts, the bravery to express the hopes that stir our souls, and the confidence to turn those hopes and those dreams into action.


Nouns: ['courage', 'dreams', 'hearts', 'bravery', 'hopes', 'souls', 'confidence', 'hopes', 'dreams', 'action']

Sentence 5:
Text: From now on, America will be empowered by our aspirations, not burdened by our fears; inspired by the future, not bound by failures of the past; and guided by our vision, not blinded by our doubts.


Nouns: ['aspirations', 'fears',

## Exercise 4. Build your own Bag Of Words implementation using tokenizer created before 

You need to implement following methods:

- ``fit_transform`` - gets a list of strings and returns matrix with it's BoW representation
- ``get_features_names`` - returns list of words corresponding to columns in BoW

In [20]:
import numpy as np
import spacy
from collections import Counter

class BagOfWords:
    """Basic BoW implementation."""
    
    __bow_list = []
    __vocabulary = None
    
    # your code goes maybe also here    
    
    def fit_transform(self, corpus: list):
        """Transform list of strings into BoW array.

        Parameters
        ----------
        corpus: List[str]
                Corpus of texts to be transforrmed

        Returns
        -------
        np.array
                Matrix representation of BoW

        """
        # your code goes here        
        processed_docs = []
        for doc in corpus:
            tokens = tokenize_words(doc.lower())
            processed_docs.append(tokens)
        
        all_tokens = [token for doc in processed_docs for token in doc]
        self.__vocabulary = sorted(set(all_tokens))
        
        bow_matrix = []
        for doc in processed_docs:
            token_counts = Counter(doc)
            doc_vector = [token_counts.get(token, 0) for token in self.__vocabulary]
            bow_matrix.append(doc_vector)
        
        return np.array(bow_matrix)

      

    def get_feature_names(self) -> list:
        """Return words corresponding to columns of matrix.

        Returns
        -------
        List[str]
                Words being transformed by fit function

        """   
        # your code goes here
        return self.__vocabulary if self.__vocabulary is not None else []

corpus = [
     'Bag Of Words is based on counting',
     'words occurences throughout multiple documents.',
     'This is the third document.',
     'As you can see most of the words occur only once.',
     'This gives us a pretty sparse matrix, see below. Really, see below',
]    
    
vectorizer = BagOfWords()

X = vectorizer.fit_transform(corpus)
print(X)

print(vectorizer.get_feature_names())
print(len(vectorizer.get_feature_names()))

[[0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1]
 [1 0 0 0 2 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 2 1 0 0 1 0 1 0 0]]
['a', 'as', 'bag', 'based', 'below', 'can', 'counting', 'document', 'documents', 'gives', 'is', 'matrix', 'most', 'multiple', 'occur', 'occurences', 'of', 'on', 'once', 'only', 'pretty', 'really', 'see', 'sparse', 'the', 'third', 'this', 'throughout', 'us', 'words', 'you']
31


## Exercise 5. Build a 5-gram model and clean up the results.

There are three tasks to do:
1. Use 5-gram model instead of 3.
2. Change to capital letter each first letter of a sentence.
3. Remove the whitespace between the last word in a sentence and . ! or ?.

Hint: for 2. and 3. implement a function called ``clean_generated()`` that takes the generated text and fix both issues at once. It could be easier to fix the text after it's generated rather then doing some changes in the while loop.

In [33]:
from nltk.book import *

wall_street = text7.tokens

import re

tokens = wall_street

def cleanup():
    compiled_pattern = re.compile("^[a-zA-Z0-9.!?]")
    clean = list(filter(compiled_pattern.match,tokens))
    return clean
tokens = cleanup()

def build_ngrams():
    ngrams = []
    for i in range(len(tokens)-N+1):
        ngrams.append(tokens[i:i+N])
    return ngrams

def ngram_freqs(ngrams):
    counts = {}

    for ngram in ngrams:
        token_seq  = SEP.join(ngram[:-1])
        last_token = ngram[-1]

        if token_seq not in counts:
            counts[token_seq] = {}

        if last_token not in counts[token_seq]:
            counts[token_seq][last_token] = 0

        counts[token_seq][last_token] += 1;

    return counts

def next_word(text, N, counts):

    token_seq = SEP.join(text.split()[-(N-1):]);
    choices = counts[token_seq].items();

    total = sum(weight for choice, weight in choices)
    r = random.uniform(0, total)
    upto = 0
    for choice, weight in choices:
        upto += weight;
        if upto > r: return choice
    assert False # should not reach here

In [44]:
def clean_generated(text):
    # put your code here
    text = re.sub(r'\s+([.!?])', r'\1', text)

    sentences = re.split(r'([.!?]\s+)', text)
    cleaned_sentences = []
    
    for i in range(0, len(sentences), 2):
        if i < len(sentences):

            sentence = sentences[i]
            punctuation = sentences[i+1] if i+1 < len(sentences) else ""
            if sentence:
                sentence = sentence[0].upper() + sentence[1:]
            cleaned_sentences.append(sentence + punctuation)
    
    return "".join(cleaned_sentences)

N=5 # fix it for other value of N

SEP=" "

sentence_count=5

ngrams = build_ngrams()
start_seq="We have to worry whether"

counts = ngram_freqs(ngrams)

if start_seq is None: start_seq = random.choice(list(counts.keys()))
generated = start_seq.lower();

sentences = 0
while sentences < sentence_count:
    generated += SEP + next_word(generated, N, counts)
    sentences += 1 if generated.endswith(('.','!', '?')) else 0

# put your code here:

cleaned_text = clean_generated(generated)

print("Original generated text:")
print(generated)
print("\nCleaned text:")
print(cleaned_text)

Original generated text:
we have to worry whether the ad is truthful . In 1989 as often as not the principal fights in the major campaigns are prompted by the ads themselves . Take a look then at the main attack commercials that set the tone for Tuesday elections in New York City of an acute anemic condition . Sony Corp. completed its tender offer for Columbia Pictures Entertainment Inc.

Cleaned text:
We have to worry whether the ad is truthful. In 1989 as often as not the principal fights in the major campaigns are prompted by the ads themselves. Take a look then at the main attack commercials that set the tone for Tuesday elections in New York City of an acute anemic condition. Sony Corp. Completed its tender offer for Columbia Pictures Entertainment Inc.
